language: go

go:
  - 1.6.2
  - tip

sudo: false

os:
  - linux

before_install:
  - go get pkg.re/essentialkaos/ek.v3

script:
  - go build examples/annotations_example.go
  - go build examples/async_example.go
  - go build examples/basic_example.go
  - go build examples/collector_example.go
