sudo: false

language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - make deps
  - mkdir -p $GOPATH/src/pkg.re/essentialkaos
  - ln -sf $GOPATH/src/github.com/essentialkaos/librato $GOPATH/src/pkg.re/essentialkaos/librato.v8

script:
  - go build examples/annotations_example.go
  - go build examples/async_example.go
  - go build examples/basic_example.go
  - go build examples/collector_example.go
