language: go

go:
  - 1.14.x
  - 1.15.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - make deps

script:
  - go build examples/annotations_example.go
  - go build examples/async_example.go
  - go build examples/basic_example.go
  - go build examples/collector_example.go
