########################################################################################

# This Makefile generated by GoMakeGen 0.6.0 using next command:
# gomakegen --metalinter .

########################################################################################

.PHONY = fmt metalinter

########################################################################################

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

metalinter:
	test -s $(GOPATH)/bin/gometalinter || (go get -u github.com/alecthomas/gometalinter ; $(GOPATH)/bin/gometalinter --install)
	$(GOPATH)/bin/gometalinter --deadline 30s

########################################################################################
